esphome:
  name: car
  friendly_name: car

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: WARN

ota:
  password: wifi_password

wifi:
  ssid: wifi_ssid
  password: wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Car Fallback Hotspot"
    password: wifi_password


web_server:
  port: 80 
  
captive_portal:
    
mqtt:
  broker: mqtt_broker
  port: 8883
  username: mqtt_username
  password: mqtt_password
  on_message:
    - topic: civic/start_engine
      qos: 2
      then:
        - lambda: |-
            if (x == "on")
              id(start_engine).turn_on();
            else if (x == "off")
              id(start_engine).turn_off();
    - topic: civic/doors
      qos: 2
      then:
        - lambda: |-
            if (x == "open")
              id(open_doors).turn_on();
            else if (x == "close")
              id(close_doors).turn_on();
    - topic: civic/on
      qos: 2
      then:
        - switch.turn_on: ignition
    - topic: civic/off
      qos: 2
      then:
        - switch.turn_off: ignition

  certificate_authority: |
    -----BEGIN CERTIFICATE-----
    MIIFazCCA1OgAwIBAgIRAIIQz7DSQONZRGPgu2OCiwAwDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMTUwNjA0MTEwNDM4
    WhcNMzUwNjA0MTEwNDM4WjBPMQswCQYDVQQGEwJVUzEpMCcGA1UEChMgSW50ZXJu
    ZXQgU2VjdXJpdHkgUmVzZWFyY2ggR3JvdXAxFTATBgNVBAMTDElTUkcgUm9vdCBY
    MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAK3oJHP0FDfzm54rVygc
    h77ct984kIxuPOZXoHj3dcKi/vVqbvYATyjb3miGbESTtrFj/RQSa78f0uoxmyF+
    0TM8ukj13Xnfs7j/EvEhmkvBioZxaUpmZmyPfjxwv60pIgbz5MDmgK7iS4+3mX6U
    A5/TR5d8mUgjU+g4rk8Kb4Mu0UlXjIB0ttov0DiNewNwIRt18jA8+o+u3dpjq+sW
    T8KOEUt+zwvo/7V3LvSye0rgTBIlDHCNAymg4VMk7BPZ7hm/ELNKjD+Jo2FR3qyH
    B5T0Y3HsLuJvW5iB4YlcNHlsdu87kGJ55tukmi8mxdAQ4Q7e2RCOFvu396j3x+UC
    B5iPNgiV5+I3lg02dZ77DnKxHZu8A/lJBdiB3QW0KtZB6awBdpUKD9jf1b0SHzUv
    KBds0pjBqAlkd25HN7rOrFleaJ1/ctaJxQZBKT5ZPt0m9STJEadao0xAH0ahmbWn
    OlFuhjuefXKnEgV4We0+UXgVCwOPjdAvBbI+e0ocS3MFEvzG6uBQE3xDk3SzynTn
    jh8BCNAw1FtxNrQHusEwMFxIt4I7mKZ9YIqioymCzLq9gwQbooMDQaHWBfEbwrbw
    qHyGO0aoSCqI3Haadr8faqU9GY/rOPNk3sgrDQoo//fb4hVC1CLQJ13hef4Y53CI
    rU7m2Ys6xt0nUW7/vGT1M0NPAgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIBBjAPBgNV
    HRMBAf8EBTADAQH/MB0GA1UdDgQWBBR5tFnme7bl5AFzgAiIyBpY9umbbjANBgkq
    hkiG9w0BAQsFAAOCAgEAVR9YqbyyqFDQDLHYGmkgJykIrGF1XIpu+ILlaS/V9lZL
    ubhzEFnTIZd+50xx+7LSYK05qAvqFyFWhfFQDlnrzuBZ6brJFe+GnY+EgPbk6ZGQ
    3BebYhtF8GaV0nxvwuo77x/Py9auJ/GpsMiu/X1+mvoiBOv/2X/qkSsisRcOj/KK
    NFtY2PwByVS5uCbMiogziUwthDyC3+6WVwW6LLv3xLfHTjuCvjHIInNzktHCgKQ5
    ORAzI4JMPJ+GslWYHb4phowim57iaztXOoJwTdwJx4nLCgdNbOhdjsnvzqvHu7Ur
    TkXWStAmzOVyyghqpZXjFaH3pO3JLF+l+/+sKAIuvtd7u+Nxe5AW0wdeRlN8NwdC
    jNPElpzVmbUq4JUagEiuTDkHzsxHpFKVK7q4+63SM1N95R1NbdWhscdCb+ZAJzVc
    oyi3B43njTOQ5yOf+1CceWxG1bQVs5ZufpsMljq4Ui0/1lvh+wjChP4kqKOJ2qxq
    4RgqsahDYVvTH9w7jXbyLeiNdd8XM2w9U/t7y0Ff/9yi0GE44Za4rF2LN9d11TPA
    mRGunUHBcnWEvgJBQl9nJEiU0Zsnvgc/ubhPgXRR4Xq37Z0j4r7g1SgEEzwxA57d
    emyPxgcYxn/eR44/KJ4EBs+lVDR3veyJm+kXQ99b21/+jh5Xos1AnX5iItreGCc=
    -----END CERTIFICATE-----

switch:
    # First 4ch relay module
  - platform: gpio
    name: "Heater"
    id: heater
    pin: GPIO14
    inverted: yes
  - platform: gpio
    name: "Media"
    id: media
    pin: GPIO27
    inverted: yes
  - platform: gpio
    name: "Starter"
    id: starter
    pin: GPIO26
    inverted: yes
    on_turn_on:
      - delay: 1500ms
      - switch.turn_off: starter
  - platform: gpio
    name: "Ignition"
    id: ignition
    pin: GPIO25
    inverted: yes

  - platform: template
    name: "Start engine"
    id: start_engine
    turn_on_action:
      - switch.turn_on: ignition
      - switch.turn_on: heater
      - delay: 5s
      - switch.turn_on: starter
    turn_off_action:
      - switch.turn_off: starter
      - switch.turn_off: ignition
      - switch.turn_off: heater

    # Second 4ch relay module
  - platform: gpio
    name: "Open doors"
    id: open_doors
    pin: GPIO4
    inverted: yes
    on_turn_on:
    - delay: 600ms
    - switch.turn_off: open_doors
    interlock: [close_doors]
  - platform: gpio
    name: "Close doors"
    id: close_doors
    pin: GPIO0
    inverted: yes
    on_turn_on:
    - delay: 600ms
    - switch.turn_off: close_doors
    interlock: [open_doors]
  - platform: gpio
    id: starter222
    pin: GPIO2
    inverted: yes
  - platform: gpio
    id: ignition222
    pin: GPIO15
    inverted: yes
    #=========================

sensor:
  - platform: uptime
    name: "Uptime Sensor"
  - platform: adc
    name: "On-board voltage"
    pin: GPIO32
    id: on_bord_voltage
    update_interval: 10s
